[package]
name = "blk-to-json"
version = "0.1.0"
edition = "2024"

[dependencies]
fltk = { version = "^1.4", features = ["fltk-bundled"] }
regex = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
dirs = "4"
anyhow = "1"